export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL'
export const CLEAR_USER_TOKEN = 'CLEAR_USER_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
export const VALIDATE_CODE = 'VALIDATE_CODE'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER2 = 'UPDATE_USER2'
export const IS_FIRST_TIME = 'IS_FIRST_TIME'
//TODO
export const CREATE_USER = 'CREATE_USER'